# coding: utf-8

"""
    aind-dataverse-service

     ## aind-dataverse-service  Service to pull data from Allen Institute's Dataverse database.  

    The version of the OpenAPI document: 0.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aind_dataverse_service_client.models.water_restriction_model import WaterRestrictionModel

class TestWaterRestrictionModel(unittest.TestCase):
    """WaterRestrictionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WaterRestrictionModel:
        """Test WaterRestrictionModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WaterRestrictionModel`
        """
        model = WaterRestrictionModel()
        if include_optional:
            return WaterRestrictionModel(
                mouse_id = '',
                protocol_id = '',
                record_name = '',
                active_record = True,
                baseline_weight = ERROR_TO_EXAMPLE_VALUE,
                last_watered_datetime = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                low_weight_threshold = ERROR_TO_EXAMPLE_VALUE,
                target_weight = ERROR_TO_EXAMPLE_VALUE,
                targeted_weight_percentage = ERROR_TO_EXAMPLE_VALUE,
                water_restriction_status = '',
                change_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                new_value = '',
                old_value = ''
            )
        else:
            return WaterRestrictionModel(
                mouse_id = '',
        )
        """

    def testWaterRestrictionModel(self):
        """Test WaterRestrictionModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
