# coding: utf-8

"""
    aind-dataverse-service

     ## aind-dataverse-service  Service to pull data from Allen Institute's Dataverse database.  

    The version of the OpenAPI document: 0.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class WaterRestrictionModel(BaseModel):
    """
    Response model for the Water Restriction API
    """ # noqa: E501
    mouse_id: Optional[StrictStr]
    protocol_id: Optional[StrictStr] = None
    record_name: Optional[StrictStr] = None
    active_record: Optional[StrictBool] = None
    baseline_weight: Optional[Annotated[str, Field(strict=True)]] = None
    last_watered_datetime: Optional[datetime] = None
    low_weight_threshold: Optional[Annotated[str, Field(strict=True)]] = None
    target_weight: Optional[Annotated[str, Field(strict=True)]] = None
    targeted_weight_percentage: Optional[Annotated[str, Field(strict=True)]] = None
    water_restriction_status: Optional[StrictStr] = None
    change_date_time: Optional[datetime] = None
    new_value: Optional[StrictStr] = None
    old_value: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["mouse_id", "protocol_id", "record_name", "active_record", "baseline_weight", "last_watered_datetime", "low_weight_threshold", "target_weight", "targeted_weight_percentage", "water_restriction_status", "change_date_time", "new_value", "old_value"]

    @field_validator('baseline_weight')
    def baseline_weight_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$", value):
            raise ValueError(r"must validate the regular expression /^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/")
        return value

    @field_validator('low_weight_threshold')
    def low_weight_threshold_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$", value):
            raise ValueError(r"must validate the regular expression /^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/")
        return value

    @field_validator('target_weight')
    def target_weight_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$", value):
            raise ValueError(r"must validate the regular expression /^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/")
        return value

    @field_validator('targeted_weight_percentage')
    def targeted_weight_percentage_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$", value):
            raise ValueError(r"must validate the regular expression /^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WaterRestrictionModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if mouse_id (nullable) is None
        # and model_fields_set contains the field
        if self.mouse_id is None and "mouse_id" in self.model_fields_set:
            _dict['mouse_id'] = None

        # set to None if protocol_id (nullable) is None
        # and model_fields_set contains the field
        if self.protocol_id is None and "protocol_id" in self.model_fields_set:
            _dict['protocol_id'] = None

        # set to None if record_name (nullable) is None
        # and model_fields_set contains the field
        if self.record_name is None and "record_name" in self.model_fields_set:
            _dict['record_name'] = None

        # set to None if active_record (nullable) is None
        # and model_fields_set contains the field
        if self.active_record is None and "active_record" in self.model_fields_set:
            _dict['active_record'] = None

        # set to None if baseline_weight (nullable) is None
        # and model_fields_set contains the field
        if self.baseline_weight is None and "baseline_weight" in self.model_fields_set:
            _dict['baseline_weight'] = None

        # set to None if last_watered_datetime (nullable) is None
        # and model_fields_set contains the field
        if self.last_watered_datetime is None and "last_watered_datetime" in self.model_fields_set:
            _dict['last_watered_datetime'] = None

        # set to None if low_weight_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.low_weight_threshold is None and "low_weight_threshold" in self.model_fields_set:
            _dict['low_weight_threshold'] = None

        # set to None if target_weight (nullable) is None
        # and model_fields_set contains the field
        if self.target_weight is None and "target_weight" in self.model_fields_set:
            _dict['target_weight'] = None

        # set to None if targeted_weight_percentage (nullable) is None
        # and model_fields_set contains the field
        if self.targeted_weight_percentage is None and "targeted_weight_percentage" in self.model_fields_set:
            _dict['targeted_weight_percentage'] = None

        # set to None if water_restriction_status (nullable) is None
        # and model_fields_set contains the field
        if self.water_restriction_status is None and "water_restriction_status" in self.model_fields_set:
            _dict['water_restriction_status'] = None

        # set to None if change_date_time (nullable) is None
        # and model_fields_set contains the field
        if self.change_date_time is None and "change_date_time" in self.model_fields_set:
            _dict['change_date_time'] = None

        # set to None if new_value (nullable) is None
        # and model_fields_set contains the field
        if self.new_value is None and "new_value" in self.model_fields_set:
            _dict['new_value'] = None

        # set to None if old_value (nullable) is None
        # and model_fields_set contains the field
        if self.old_value is None and "old_value" in self.model_fields_set:
            _dict['old_value'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WaterRestrictionModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mouse_id": obj.get("mouse_id"),
            "protocol_id": obj.get("protocol_id"),
            "record_name": obj.get("record_name"),
            "active_record": obj.get("active_record"),
            "baseline_weight": obj.get("baseline_weight"),
            "last_watered_datetime": obj.get("last_watered_datetime"),
            "low_weight_threshold": obj.get("low_weight_threshold"),
            "target_weight": obj.get("target_weight"),
            "targeted_weight_percentage": obj.get("targeted_weight_percentage"),
            "water_restriction_status": obj.get("water_restriction_status"),
            "change_date_time": obj.get("change_date_time"),
            "new_value": obj.get("new_value"),
            "old_value": obj.get("old_value")
        })
        return _obj


